version: '3'

includes:
  cargo:
    taskfile: ./mono-dev/task/cargo.yaml
    optional: true
    internal: true

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install cargo-watch live-server

  install:
    cmds:
      - rm -rf mono-dev
      - git clone https://github.com/Pistonight/mono-dev --depth 1

  test:
    cmds:
      - cargo test
      - cargo test --no-default-features
      - cargo test --features thread-safe

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

  dev-doc:
    cmds:
      - task: cargo:watch-serve-doc


