name: Rust
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true
      - uses: ./.github/steps/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: task install
      - run: task check

  build:
    name: Build, Test
    strategy: { matrix: { os: [ ubuntu-latest, macos-latest, windows-latest ] } }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true
      - uses: ./.github/steps/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo test
      - run: cargo test --no-default-features
      - run: cargo test --features thread-safe
